name: Update Leaderboard

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Function
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          curl -X POST \
            --http1.1 \
            -v \
            -H "Authorization: Bearer $SECRET_TOKEN" \
            https://play.suicityp2e.com/.netlify/functions/update-leaderboard
