name: Update Leaderboard

on:
  schedule:
    - cron: "*/2 * * * *" # Runs every 2 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Function
        run: |
          curl -X POST \
            --http1.1 \
            -v \
            -H "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" \
            https://play.suicityp2e.com/.netlify/functions/update-leaderboard
